FROM node:14

RUN apt-get update
RUN apt-get install -y make libstdc++
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# Install dependecies first (and keep them cached)
COPY app/package.json /usr/src/app/
RUN npm install

COPY app/ /usr/src/app

EXPOSE 6000
EXPOSE 6100
EXPOSE 6200

CMD ["npm", "run", "start"]